import type { CSSProperties } from 'react';
import { colors, font, radius, shadow, spacing } from '../../theme/tokens';

export function getNotificationToneStyle(tone: 'info' | 'warning' | 'success'): CSSProperties {
  if (tone === 'warning') {
    return { backgroundColor: colors.status.warning };
  }

  if (tone === 'success') {
    return { backgroundColor: colors.status.ok };
  }

  return { backgroundColor: colors.brand.primary };
}

export const shellStyles: Record<string, CSSProperties> = {
  badge: {
    alignItems: 'center',
    backgroundColor: colors.brand.primary,
    borderRadius: 999,
    color: colors.brand.foreground,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: 10,
    fontWeight: font.weight.bold,
    height: 16,
    justifyContent: 'center',
    minWidth: 16,
    padding: '0 4px',
    position: 'absolute',
    right: -5,
    top: -5,
  },
  brandBadge: {
    alignItems: 'center',
    backgroundColor: colors.brand.primary,
    borderRadius: radius.sm,
    color: colors.brand.foreground,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.xs,
    fontWeight: font.weight.bold,
    height: 32,
    justifyContent: 'center',
    letterSpacing: 0,
    width: 32,
  },
  brandBlock: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.space2,
    minHeight: 40,
    padding: `0 ${spacing.space4}px`,
  },
  brandBlockCollapsed: {
    justifyContent: 'center',
  },
  brandSubtitle: {
    color: colors.text.secondary,
    fontSize: font.size.small,
    marginTop: 1,
  },
  brandTitle: {
    color: colors.text.primary,
    fontSize: font.size.body,
    fontWeight: font.weight.semibold,
  },
  header: {
    backgroundColor: colors.surface,
    borderBottom: `1px solid ${colors.border}`,
    boxShadow: 'none',
    display: 'flex',
    gap: spacing.space4,
    minHeight: 64,
    minWidth: 0,
    padding: `0 ${spacing.space6}px`,
    position: 'sticky',
    top: 0,
    zIndex: 30,
  },
  headerActions: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.space2,
    marginLeft: 'auto',
  },
  headerStart: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.space2,
    minWidth: 0,
  },
  headerIntro: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    minWidth: 0,
  },
  headerKicker: {
    color: colors.text.muted,
    fontFamily: font.mono,
    fontSize: font.size.small,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    color: colors.text.secondary,
    fontSize: font.size.small,
    lineHeight: 1.5,
  },
  headerTitle: {
    color: colors.text.primary,
    fontSize: font.size.h3,
    fontWeight: font.weight.semibold,
    lineHeight: 1.25,
  },
  iconButton: {
    ...createInteractiveButtonStyle({
      backgroundColor: 'transparent',
      backgroundHoverColor: colors.accentSoft,
      borderColor: colors.border,
      borderHoverColor: colors.borderStrong,
      color: colors.text.primary,
    }),
    alignItems: 'center',
    borderRadius: radius.sm,
    cursor: 'pointer',
    display: 'flex',
    height: 34,
    justifyContent: 'center',
    position: 'relative',
    width: 34,
  },
  inlineAction: {
    ...createInteractiveButtonStyle({
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      color: colors.brand.primary,
      colorHover: colors.brand.primaryHover,
    }),
    border: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  search: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.text.muted,
    display: 'flex',
    gap: spacing.space2,
    height: 34,
    minWidth: 260,
    padding: '0 8px',
  },
  searchInput: {
    backgroundColor: 'transparent',
    border: 'none',
    color: colors.text.primary,
    flex: 1,
    fontSize: font.size.body,
    minWidth: 0,
    padding: 0,
  },
  searchShortcut: {
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.text.muted,
    fontSize: 10,
    lineHeight: 1,
    padding: '3px 5px',
  },
  main: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    minWidth: 0,
  },
  menuButton: {
    ...createInteractiveButtonStyle({
      backgroundColor: 'transparent',
      backgroundHoverColor: colors.accentSoft,
      borderColor: colors.border,
      borderHoverColor: colors.borderStrong,
      color: colors.text.primary,
    }),
    alignItems: 'center',
    borderRadius: radius.sm,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.space2,
    padding: '9px 10px',
    width: '100%',
  },
  navButton: {
    alignItems: 'center',
    borderRadius: radius.md,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.space3,
    minHeight: 40,
    outline: 'none',
    padding: '10px 12px',
    textAlign: 'left',
    WebkitTapHighlightColor: 'transparent',
    width: '100%',
    transition: 'all 0.12s ease',
  },
  navButtonCollapsed: {
    justifyContent: 'center',
    padding: '7px',
  },
  navGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.space2,
  },
  navGroupLabel: {
    color: colors.text.muted,
    fontSize: font.size.small,
    fontWeight: font.weight.medium,
    letterSpacing: 0,
    padding: `0 10px`,
  },
  navIconWrap: {
    alignItems: 'center',
    borderRadius: radius.sm,
    display: 'flex',
    height: 18,
    justifyContent: 'center',
    minWidth: 18,
  },
  navLabel: {
    color: 'inherit',
    fontSize: font.size.body,
    fontWeight: font.weight.medium,
  },
  navList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.space1,
    padding: `0 ${spacing.space2}px`,
  },
  navStack: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: spacing.space4,
  },
  navTextWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
  },
  notificationBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
  },
  notificationCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.text.primary,
    cursor: 'pointer',
    display: 'grid',
    gap: spacing.space2,
    gridTemplateColumns: '8px minmax(0, 1fr) auto',
    padding: spacing.space2,
    textAlign: 'left',
    width: '100%',
  },
  notificationCardRead: {
    opacity: 0.68,
  },
  notificationDetail: {
    color: colors.text.secondary,
    fontSize: font.size.small,
    lineHeight: 1.5,
  },
  notificationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.space2,
  },
  notificationTime: {
    color: colors.text.muted,
    fontFamily: font.mono,
    fontSize: font.size.small,
    marginTop: 2,
  },
  notificationTitle: {
    color: colors.text.primary,
    fontSize: font.size.body,
    fontWeight: font.weight.semibold,
  },
  notificationTone: {
    borderRadius: 999,
    height: 8,
    marginTop: 6,
    width: 8,
  },
  notificationsPopover: {
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    boxShadow: shadow.card,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    padding: spacing.md,
    position: 'absolute',
    right: spacing.md,
    top: 48,
    width: 'min(360px, calc(100vw - 32px))',
    zIndex: 60,
  },
  popoverCaption: {
    color: colors.text.muted,
    fontSize: font.size.sm,
    marginTop: 2,
  },
  popoverHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  popoverTitle: {
    color: colors.text.primary,
    fontSize: font.size.md,
    fontWeight: font.weight.bold,
  },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: colors.brand.primary,
    borderRadius: 999,
    color: colors.brand.foreground,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.xs,
    fontWeight: font.weight.bold,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  profileAvatarLarge: {
    alignItems: 'center',
    backgroundColor: colors.brand.primary,
    borderRadius: radius.sm,
    color: colors.brand.foreground,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.md,
    fontWeight: font.weight.bold,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  profileButton: {
    ...createInteractiveButtonStyle({
      backgroundColor: 'transparent',
      backgroundHoverColor: colors.accentSoft,
      borderColor: colors.border,
      borderHoverColor: colors.borderStrong,
      color: colors.text.primary,
    }),
    alignItems: 'center',
    borderRadius: radius.sm,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.sm,
    minHeight: 34,
    padding: '3px 8px 3px 3px',
  },
  profileMeta: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  profileName: {
    color: colors.text.primary,
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
  },
  profilePopover: {
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    boxShadow: shadow.card,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    padding: spacing.md,
    position: 'absolute',
    right: spacing.md,
    top: 48,
    width: 'min(340px, calc(100vw - 32px))',
    zIndex: 60,
  },
  profilePopoverHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.md,
  },
  profileRole: {
    color: colors.text.muted,
    fontSize: font.size.xs,
  },
  profileThemeBlock: {
    borderTop: `1px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.md,
  },
  profileThemeGrid: {
    display: 'grid',
    gap: spacing.sm,
  },
  sidebar: {
    alignSelf: 'start',
    backgroundColor: colors.bgSidebar,
    border: 'none',
    borderRight: `1px solid ${colors.border}`,
    borderRadius: 0,
    boxShadow: 'none',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.space4,
    height: '100vh',
    overflowY: 'auto',
    padding: `${spacing.space2}px 0`,
    position: 'sticky',
    scrollbarGutter: 'stable',
    top: 0,
  },
  sidebarCollapsed: {
    alignItems: 'center',
  },
  statusWrap: {
    marginTop: 'auto',
    padding: `0 ${spacing.sm}px`,
  },
  statusWrapCollapsed: {
    width: '100%',
  },
  themeOptionButton: {
    ...createInteractiveButtonStyle({
      backgroundColor: colors.surface,
      backgroundHoverColor: colors.accentSoft,
      borderColor: colors.border,
      borderHoverColor: colors.borderStrong,
      color: colors.text.primary,
    }),
    borderRadius: radius.sm,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: spacing.sm,
    textAlign: 'left',
  },
  themeOptionButtonActive: {
    backgroundColor: colors.accentSoft,
    border: `1px solid ${colors.accent}`,
  },
  themeOptionDescription: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.5,
  },
  themeOptionTitle: {
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
  },
};
