import type { CSSProperties } from 'react';
import { colors, font, radius, shadow, spacing } from '../../theme/tokens';

export function getNotificationToneStyle(tone: 'info' | 'warning' | 'success'): CSSProperties {
  if (tone === 'warning') {
    return { backgroundColor: colors.status.warning };
  }

  if (tone === 'success') {
    return { backgroundColor: colors.status.ok };
  }

  return { backgroundColor: colors.accent };
}

export const shellStyles: Record<string, CSSProperties> = {
  badge: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 999,
    color: colors.accentContrast,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: 10,
    fontWeight: font.weight.bold,
    height: 18,
    justifyContent: 'center',
    minWidth: 18,
    padding: '0 4px',
    position: 'absolute',
    right: -4,
    top: -4,
  },
  brandBadge: {
    alignItems: 'center',
    background: `linear-gradient(135deg, ${colors.accent}, ${colors.status.ok})`,
    borderRadius: radius.md,
    color: colors.accentContrast,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.md,
    fontWeight: font.weight.bold,
    height: 48,
    justifyContent: 'center',
    letterSpacing: '0.08em',
    width: 48,
  },
  brandBlock: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.md,
    padding: `0 ${spacing.md}px`,
  },
  brandBlockCollapsed: {
    justifyContent: 'center',
  },
  brandSubtitle: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    marginTop: 2,
  },
  brandTitle: {
    color: colors.text.primary,
    fontSize: font.size.lg,
    fontWeight: font.weight.bold,
  },
  header: {
    backgroundColor: colors.surface,
    backdropFilter: 'blur(22px)',
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xl,
    boxShadow: shadow.soft,
    minWidth: 0,
    padding: spacing.lg,
    position: 'relative',
    zIndex: 30,
  },
  headerActions: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
    position: 'absolute',
    right: spacing.lg,
    top: spacing.lg,
  },
  headerIntro: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    maxWidth: 720,
    paddingRight: 240,
  },
  headerKicker: {
    color: colors.accent,
    fontFamily: font.mono,
    fontSize: font.size.xs,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    color: colors.text.secondary,
    fontSize: font.size.md,
    lineHeight: 1.6,
  },
  headerTitle: {
    color: colors.text.primary,
    fontSize: font.size.xxl,
    fontWeight: font.weight.bold,
    lineHeight: 1,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.text.primary,
    cursor: 'pointer',
    display: 'flex',
    height: 46,
    justifyContent: 'center',
    position: 'relative',
    width: 46,
  },
  inlineAction: {
    backgroundColor: 'transparent',
    border: 'none',
    color: colors.accent,
    cursor: 'pointer',
    padding: 0,
  },
  main: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
    minWidth: 0,
  },
  menuButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.text.primary,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.sm,
    padding: '12px 14px',
    width: '100%',
  },
  navButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    border: `1px solid transparent`,
    borderRadius: radius.lg,
    color: colors.text.secondary,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.md,
    padding: '12px 14px',
    textAlign: 'left',
    width: '100%',
  },
  navButtonActive: {
    backgroundColor: colors.accentSoft,
    border: `1px solid ${colors.borderStrong}`,
    color: colors.text.primary,
  },
  navButtonCollapsed: {
    justifyContent: 'center',
    padding: '12px',
  },
  navGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  navGroupLabel: {
    color: colors.text.muted,
    fontFamily: font.mono,
    fontSize: font.size.xs,
    letterSpacing: '0.16em',
    padding: `0 ${spacing.md}px`,
    textTransform: 'uppercase',
  },
  navIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.text.secondary,
    display: 'flex',
    height: 38,
    justifyContent: 'center',
    minWidth: 38,
  },
  navIconWrapActive: {
    backgroundColor: colors.accent,
    border: `1px solid ${colors.accent}`,
    color: colors.accentContrast,
  },
  navLabel: {
    color: 'inherit',
    fontSize: font.size.md,
    fontWeight: font.weight.semibold,
  },
  navList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xs,
    padding: `0 ${spacing.sm}px`,
  },
  navStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  navTextWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
  },
  notificationBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
  },
  notificationCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.text.primary,
    cursor: 'pointer',
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: '8px minmax(0, 1fr) auto',
    padding: spacing.md,
    textAlign: 'left',
    width: '100%',
  },
  notificationCardRead: {
    opacity: 0.68,
  },
  notificationDetail: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.5,
  },
  notificationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  notificationTime: {
    color: colors.text.muted,
    fontFamily: font.mono,
    fontSize: font.size.xs,
    marginTop: 2,
  },
  notificationTitle: {
    color: colors.text.primary,
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
  },
  notificationTone: {
    borderRadius: 999,
    height: 8,
    marginTop: 6,
    width: 8,
  },
  notificationsPopover: {
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: radius.lg,
    boxShadow: shadow.card,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    padding: spacing.md,
    position: 'absolute',
    right: spacing.lg,
    top: 86,
    width: 'min(420px, calc(100vw - 56px))',
    zIndex: 60,
  },
  popoverCaption: {
    color: colors.text.muted,
    fontSize: font.size.sm,
    marginTop: 2,
  },
  popoverHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  popoverTitle: {
    color: colors.text.primary,
    fontSize: font.size.md,
    fontWeight: font.weight.bold,
  },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 999,
    color: colors.accentContrast,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.xs,
    fontWeight: font.weight.bold,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  profileAvatarLarge: {
    alignItems: 'center',
    background: `linear-gradient(135deg, ${colors.accent}, ${colors.status.ok})`,
    borderRadius: radius.lg,
    color: colors.accentContrast,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.md,
    fontWeight: font.weight.bold,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  profileButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.text.primary,
    cursor: 'pointer',
    display: 'flex',
    gap: spacing.sm,
    padding: '8px 12px',
  },
  profileMeta: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  profileName: {
    color: colors.text.primary,
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
  },
  profilePopover: {
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: radius.lg,
    boxShadow: shadow.card,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    padding: spacing.md,
    position: 'absolute',
    right: spacing.lg,
    top: 86,
    width: 'min(420px, calc(100vw - 56px))',
    zIndex: 60,
  },
  profilePopoverHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: spacing.md,
  },
  profileRole: {
    color: colors.text.muted,
    fontSize: font.size.xs,
  },
  profileThemeBlock: {
    borderTop: `1px solid ${colors.border}`,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.md,
  },
  profileThemeGrid: {
    display: 'grid',
    gap: spacing.sm,
  },
  sidebar: {
    alignSelf: 'start',
    backgroundColor: colors.surface,
    backdropFilter: 'blur(22px)',
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xl,
    boxShadow: shadow.card,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
    height: '100vh',
    overflowY: 'auto',
    padding: `${spacing.md}px 0`,
    position: 'sticky',
    scrollbarGutter: 'stable',
    top: 0,
  },
  sidebarCollapsed: {
    alignItems: 'center',
  },
  statusWrap: {
    padding: `0 ${spacing.sm}px`,
  },
  statusWrapCollapsed: {
    width: '100%',
  },
  themeOptionButton: {
    backgroundColor: colors.surfaceMuted,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.text.primary,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: spacing.md,
    textAlign: 'left',
  },
  themeOptionButtonActive: {
    backgroundColor: colors.accentSoft,
    border: `1px solid ${colors.accent}`,
  },
  themeOptionDescription: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.5,
  },
  themeOptionTitle: {
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
  },
};
