import type { CSSProperties } from 'react';
import { colors, font, radius, spacing } from '../../theme/tokens';

export const trafficLightStyles: Record<'green' | 'yellow' | 'red', CSSProperties> = {
  green: {
    backgroundColor: 'rgba(34, 197, 94, 0.18)',
    color: colors.status.ok,
  },
  red: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
    color: colors.status.error,
  },
  yellow: {
    backgroundColor: 'rgba(245, 158, 11, 0.18)',
    color: colors.status.warning,
  },
};

export const dashboardLandingStyles: Record<string, CSSProperties> = {
  activityDate: {
    color: colors.text.muted,
    fontSize: font.size.xs,
  },
  activityList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  activityMeta: {
    alignItems: 'flex-end',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  activityRow: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  activityText: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.5,
    marginTop: 4,
  },
  activityTitle: {
    color: colors.text.primary,
    fontSize: font.size.md,
    fontWeight: font.weight.semibold,
  },
  benchmarkList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  benchmarkRow: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  contentGrid: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
  },
  coverageHero: {
    alignItems: 'flex-end',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.lg,
  },
  coverageLabel: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.6,
    marginTop: 6,
    maxWidth: 340,
  },
  coverageMiniLabel: {
    color: colors.text.muted,
    fontSize: font.size.xs,
    textTransform: 'uppercase',
  },
  coverageMiniValue: {
    color: colors.accent,
    fontSize: font.size.lg,
    fontWeight: font.weight.bold,
  },
  coverageStat: {
    alignItems: 'flex-end',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  coverageValue: {
    color: colors.text.primary,
    fontSize: 'clamp(2rem, 4vw, 2.75rem)',
    fontWeight: font.weight.bold,
    letterSpacing: '-0.05em',
  },
  hero: {
    background: `linear-gradient(135deg, ${colors.surface} 0%, ${colors.surfaceElevated} 42%, ${colors.accentSoft} 100%)`,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xl,
    boxShadow: `0 18px 50px ${colors.shadow}`,
    display: 'grid',
    gap: spacing.lg,
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    overflow: 'hidden',
    padding: spacing.xl,
    position: 'relative',
  },
  heroActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  heroCopy: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
    minWidth: 0,
  },
  heroPanel: {
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
    justifyContent: 'space-between',
    minWidth: 0,
    padding: spacing.lg,
  },
  heroText: {
    color: colors.text.secondary,
    fontSize: font.size.md,
    lineHeight: 1.7,
    margin: 0,
    maxWidth: 620,
  },
  heroTitle: {
    color: colors.text.primary,
    fontSize: 'clamp(2.2rem, 4.5vw, 3.25rem)',
    fontWeight: font.weight.bold,
    letterSpacing: '-0.04em',
    lineHeight: 0.95,
    margin: 0,
    maxWidth: 720,
  },
  kicker: {
    color: colors.accent,
    fontFamily: font.mono,
    fontSize: font.size.xs,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  liveChip: {
    backgroundColor: colors.surfaceMuted,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
    padding: spacing.md,
  },
  liveChipLabel: {
    color: colors.text.muted,
    fontSize: font.size.xs,
    textTransform: 'uppercase',
  },
  liveChipValue: {
    alignItems: 'center',
    color: colors.text.primary,
    display: 'flex',
    fontSize: font.size.sm,
    gap: 8,
    textTransform: 'capitalize',
  },
  metricCaption: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.6,
    marginTop: spacing.sm,
  },
  metricCard: {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    boxShadow: `0 14px 40px ${colors.shadow}`,
    minWidth: 0,
    padding: spacing.lg,
  },
  metricGrid: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
  },
  metricLabel: {
    color: colors.text.muted,
    fontFamily: font.mono,
    fontSize: font.size.xs,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  metricTag: {
    alignItems: 'center',
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    color: colors.text.primary,
    display: 'flex',
    fontFamily: font.mono,
    fontSize: font.size.xs,
    height: 32,
    justifyContent: 'center',
    minWidth: 32,
    padding: '0 10px',
  },
  metricValue: {
    color: colors.text.primary,
    fontSize: 34,
    fontWeight: font.weight.bold,
    letterSpacing: '-0.04em',
    marginTop: spacing.sm,
  },
  panelEyebrow: {
    color: colors.text.muted,
    fontFamily: font.mono,
    fontSize: font.size.xs,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  panelFooter: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
    lineHeight: 1.5,
  },
  panelGrid: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
    width: '100%',
  },
  sectionCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
    minWidth: 0,
  },
  spotLightValue: {
    color: colors.text.primary,
    fontSize: font.size.lg,
    fontWeight: font.weight.bold,
  },
  spotlightList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  spotlightRow: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  spotlightScore: {
    alignItems: 'flex-end',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  statusBadge: {
    backgroundColor: colors.accentSoft,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: 999,
    color: colors.text.primary,
    fontSize: font.size.xs,
    padding: '5px 10px',
    textTransform: 'capitalize',
  },
  statusMetric: {
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    padding: spacing.md,
  },
  statusMetricLabel: {
    alignItems: 'center',
    color: colors.text.secondary,
    display: 'flex',
    fontSize: font.size.sm,
    gap: 8,
  },
  statusMetricValue: {
    color: colors.text.primary,
    fontSize: 28,
    fontWeight: font.weight.bold,
  },
  statusRail: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
  },
  systemErrorText: {
    color: '#fecaca',
    fontSize: font.size.sm,
  },
  systemErrors: {
    backgroundColor: 'rgba(127, 29, 29, 0.72)',
    border: '1px solid rgba(252, 165, 165, 0.2)',
    borderRadius: radius.md,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: spacing.md,
  },
  systemGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  systemLabel: {
    color: colors.text.secondary,
    fontSize: font.size.sm,
  },
  systemRow: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  systemValue: {
    alignItems: 'center',
    color: colors.text.primary,
    display: 'flex',
    fontSize: font.size.sm,
    gap: 8,
    textTransform: 'capitalize',
  },
  trafficLight: {
    borderRadius: 999,
    fontSize: font.size.xs,
    padding: '4px 10px',
    textTransform: 'uppercase',
  },
};
