import type { Request, Response } from 'express';
import { controllers } from './controllers';

export interface RouteDefinition {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH';
  path: string;
  handler: (req: Request, res: Response) => void;
}

export const routes: RouteDefinition[] = [
  { method: 'GET', path: '/health', handler: (req, res) => controllers.health.getHealth(req, res) },
  { method: 'GET', path: '/health/db', handler: (req, res) => controllers.health.getDbHealth(req, res) },
  { method: 'GET', path: '/dashboard', handler: (req, res) => controllers.dashboard.overview(req, res) },
  { method: 'GET', path: '/dashboard/summary', handler: (req, res) => controllers.dashboard.summary(req, res) },
  { method: 'GET', path: '/dashboard/workflow-status', handler: (req, res) => controllers.dashboard.workflowStatus(req, res) },
  { method: 'GET', path: '/dashboard/lab-queue', handler: (req, res) => controllers.dashboard.labQueue(req, res) },
  { method: 'GET', path: '/dashboard/latest-scores', handler: (req, res) => controllers.dashboard.latestScores(req, res) },
  { method: 'GET', path: '/dashboard/risk-alerts', handler: (req, res) => controllers.dashboard.riskAlerts(req, res) },
  { method: 'GET', path: '/dashboard/recent-reports', handler: (req, res) => controllers.dashboard.recentReports(req, res) },
  { method: 'GET', path: '/dashboard/benchmark-overview', handler: (req, res) => controllers.dashboard.benchmarkOverview(req, res) },
  { method: 'GET', path: '/library/:resource/options', handler: (req, res) => controllers.library.options(req, res) },
  { method: 'GET', path: '/library/:resource', handler: (req, res) => controllers.library.list(req, res) },
  { method: 'POST', path: '/library/:resource', handler: (req, res) => controllers.library.create(req, res) },
  { method: 'PUT', path: '/library/:resource/:id', handler: (req, res) => controllers.library.update(req, res) },
  { method: 'PUT', path: '/library/:resource/:id/archive', handler: (req, res) => controllers.library.archive(req, res) },
  { method: 'GET', path: '/formulations/options', handler: (req, res) => controllers.formulations.options(req, res) },
  { method: 'GET', path: '/formulations', handler: (req, res) => controllers.formulations.list(req, res) },
  { method: 'POST', path: '/formulations', handler: (req, res) => controllers.formulations.create(req, res) },
  { method: 'GET', path: '/formulations/:id', handler: (req, res) => controllers.formulations.detail(req, res) },
  { method: 'PUT', path: '/formulations/:id', handler: (req, res) => controllers.formulations.update(req, res) },
  { method: 'PUT', path: '/formulations/:id/approve', handler: (req, res) => controllers.formulations.approve(req, res) },
  { method: 'PUT', path: '/formulations/:id/archive', handler: (req, res) => controllers.formulations.archive(req, res) },
  { method: 'POST', path: '/formulations/:id/duplicate', handler: (req, res) => controllers.formulations.duplicate(req, res) },
  { method: 'POST', path: '/setup-sheet-imports/preview', handler: (req, res) => controllers.processSetups.preview(req, res) },
  { method: 'GET', path: '/setup-sheet-imports/:id', handler: (req, res) => controllers.processSetups.getImport(req, res) },
  { method: 'POST', path: '/setup-sheet-imports/:id/commit', handler: (req, res) => controllers.processSetups.commit(req, res) },
  { method: 'GET', path: '/process-setups', handler: (req, res) => controllers.processSetups.list(req, res) },
  { method: 'GET', path: '/process-setups/:id', handler: (req, res) => controllers.processSetups.detail(req, res) },
  { method: 'GET', path: '/production-runs/approved-formulations', handler: (req, res) => controllers.productionRuns.approvedFormulations(req, res) },
  { method: 'GET', path: '/production-runs', handler: (req, res) => controllers.productionRuns.list(req, res) },
  { method: 'POST', path: '/production-runs', handler: (req, res) => controllers.productionRuns.create(req, res) },
  { method: 'GET', path: '/production-runs/:id', handler: (req, res) => controllers.productionRuns.detail(req, res) },
  { method: 'GET', path: '/production-runs/:id/process-setup', handler: (req, res) => controllers.processSetups.runDetail(req, res) },
  { method: 'PATCH', path: '/production-runs/:id/process-values', handler: (req, res) => controllers.processSetups.updateRunValues(req, res) },
  { method: 'PATCH', path: '/production-runs/:id', handler: (req, res) => controllers.productionRuns.update(req, res) },
  { method: 'POST', path: '/production-runs/:id/archive', handler: (req, res) => controllers.productionRuns.archive(req, res) },
  { method: 'POST', path: '/production-runs/:id/status', handler: (req, res) => controllers.productionRuns.updateStatus(req, res) },
  { method: 'GET', path: '/production-runs/:id/samples', handler: (req, res) => controllers.samples.listByRun(req, res) },
  { method: 'POST', path: '/production-runs/:id/samples/generate', handler: (req, res) => controllers.samples.generate(req, res) },
  { method: 'PATCH', path: '/samples/:id', handler: (req, res) => controllers.samples.update(req, res) },
  { method: 'POST', path: '/samples/:id/archive', handler: (req, res) => controllers.samples.archive(req, res) },
  { method: 'GET', path: '/lab-testing/queue', handler: (req, res) => controllers.labTesting.queue(req, res) },
  { method: 'GET', path: '/lab-testing/runs/:runId', handler: (req, res) => controllers.labTesting.run(req, res) },
  { method: 'GET', path: '/lab-testing/runs/:runId/samples', handler: (req, res) => controllers.labTesting.samples(req, res) },
  { method: 'GET', path: '/lab-testing/runs/:runId/results', handler: (req, res) => controllers.labTesting.results(req, res) },
  { method: 'POST', path: '/lab-testing/results', handler: (req, res) => controllers.sampleResults.create(req, res) },
  { method: 'PATCH', path: '/lab-testing/results/:resultId', handler: (req, res) => controllers.sampleResults.update(req, res) },
  { method: 'POST', path: '/lab-testing/observations', handler: (req, res) => controllers.observations.create(req, res) },
  { method: 'PATCH', path: '/lab-testing/observations/:observationId', handler: (req, res) => controllers.observations.update(req, res) },
  { method: 'POST', path: '/lab-testing/environmental-results', handler: (req, res) => controllers.environmentalResults.create(req, res) },
  { method: 'PATCH', path: '/lab-testing/environmental-results/:resultId', handler: (req, res) => controllers.environmentalResults.update(req, res) },
  { method: 'POST', path: '/lab-testing/subjective-ratings', handler: (req, res) => controllers.subjectiveRatings.create(req, res) },
  { method: 'PATCH', path: '/lab-testing/subjective-ratings/:ratingId', handler: (req, res) => controllers.subjectiveRatings.update(req, res) },
  { method: 'POST', path: '/lab-testing/runs/:runId/start', handler: (req, res) => controllers.labTesting.start(req, res) },
  { method: 'POST', path: '/lab-testing/runs/:runId/complete', handler: (req, res) => controllers.labTesting.complete(req, res) },
  { method: 'GET', path: '/run-summaries/runs/:runId', handler: (req, res) => controllers.runSummaries.detail(req, res) },
  { method: 'POST', path: '/run-summaries/runs/:runId/generate', handler: (req, res) => controllers.runSummaries.generate(req, res) },
  { method: 'POST', path: '/run-summaries/runs/:runId/regenerate', handler: (req, res) => controllers.runSummaries.regenerate(req, res) },
  { method: 'GET', path: '/run-summaries/runs/:runId/missing-required-metrics', handler: (req, res) => controllers.runSummaries.missingRequiredMetrics(req, res) },
  { method: 'GET', path: '/benchmark-scoring/runs/:runId', handler: (req, res) => controllers.benchmarkScoring.runScores(req, res) },
  { method: 'POST', path: '/benchmark-scoring/runs/:runId/generate', handler: (req, res) => controllers.benchmarkScoring.generate(req, res) },
  { method: 'POST', path: '/benchmark-scoring/runs/:runId/regenerate', handler: (req, res) => controllers.benchmarkScoring.regenerate(req, res) },
  { method: 'GET', path: '/benchmark-scoring/runs/:runId/compare', handler: (req, res) => controllers.benchmarkScoring.compare(req, res) },
  { method: 'GET', path: '/benchmark-scoring/reports/:scoreReportId', handler: (req, res) => controllers.benchmarkScoring.report(req, res) },
  { method: 'GET', path: '/reports', handler: (req, res) => controllers.reports.list(req, res) },
  { method: 'GET', path: '/reports/runs/:runId', handler: (req, res) => controllers.reports.latestForRun(req, res) },
  { method: 'POST', path: '/reports/runs/:runId/generate', handler: (req, res) => controllers.reports.generate(req, res) },
  { method: 'POST', path: '/reports/runs/:runId/regenerate', handler: (req, res) => controllers.reports.regenerate(req, res) },
  { method: 'GET', path: '/reports/:reportId/export/pdf', handler: (req, res) => controllers.reports.exportPdf(req, res) },
  { method: 'GET', path: '/reports/:reportId/export/csv', handler: (req, res) => controllers.reports.exportCsv(req, res) },
  { method: 'GET', path: '/reports/:reportId', handler: (req, res) => controllers.reports.detail(req, res) },
  { method: 'GET', path: '/version', handler: (req, res) => controllers.version.getVersion(req, res) },
];
